### PR TITLE
Fix a sometimes-broken display in chrome.

### PR DESCRIPTION
**Pull request by sstanovnik**
This took a while to fix. It was only sometimes broken, only in Chrome, with no apparent cause. Now it works consistently.

### CODE REVIEW

**Comment by gregorjerse** [comment]
Nice work. I have a feeling that columns that are empty (for instance empty classroom on Tuesday) collapse. I do not believe that happened on a previous version of the layout engine. But maybe that is OK  when your screen width is very limited.

**Comment by sstanovnik** [comment]
Empty columns don't collapse for me in Firefox, Edge or Chrome. They all stay the same width, unless there is non-breakable text in an item that forces its column to have that minimal width. Can you reproduce and post a screenshot?

**Comment by gregorjerse** [comment]
Sure. See https://photos.app.goo.gl/6ojyEwhU0sOU8KNC3 .

One more thing. The separating lines are drawn between consecutive days only when there is some activity in the second day. I thing it should always be there. See https://urnik.fri.uni-lj.si/timetable/fri-2017_2018-letni-1-teden/authenticated_allocations?teacher=75 (or any other timetable) for example.

**Comment by sstanovnik** [comment]
See #20 and #21.

**Pull request merged**
